<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
use Laminas\I18n\Translator\Translator;
$translator = new Translator();
$translator->addTranslationFile("gettext", __DIR__."/../../../User/language/{$_COOKIE["langue"]}.mo");
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <script>
        function changeLanguage(selectedObject) {
            var langue = selectedObject.value;
            document.cookie = "langue="+langue;
            location.reload();
        }
        </script>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <div class="container">
            <header class="brand-header py-3">

                <div class="row flex-nowrap justify-content-between align-items-center">
                    <div class="col-4 pt-1">
                        <select id="language" onChange="changeLanguage(this)">
                            <?php 
                                if($_COOKIE["langue"] == "fr"){
                                    echo '<option value="fr">Français</option> <option value="en">English</option>' ;
                                } else{
                                    echo '<option value="en">English</option> <option value="fr">Français</option>' ;
                                }
                            ?>
                        </select>
                    </div>

                    <div class="logo col-4 text-center">
                        <a href="<?= $this->url('home'); ?>">
                            Projet PHP Laminas
                        </a>
                    </div>

                    <div class="col-4 d-flex justify-content-end align-items-center">
                        <?php if($this->identity()) { ?>
                        <a href="<?= $this->url('profile'); ?>" class="btn btn-sm btn-outline-secondary">
                            <?php echo $translator->translate('Profil'); ?>
                        </a>
                        <a href="<?= $this->url('logout'); ?>" class="btn btn-sm btn-outline-secondary">
                        <?php echo $translator->translate('Se déconnecter'); ?>
                        </a>
                        <?php } else { ?>
                            <a href="<?= $this->url('login'); ?>" class="btn btn-sm btn-outline-secondary mr-2">
                            <?php echo $translator->translate('Se connecter'); ?>
                            </a>
                            <a href="<?= $this->url('signup'); ?>" class="btn btn-sm btn-outline-secondary">
                            <?php echo $translator->translate('S\'inscrire'); ?>
                            </a>

                        <?php } ?>
                    </div>

                </div>     
                       
            </header>
        </div>
        <div class="container">
            <?= $this->partial('flash.phtml',$this->flashMessenger()); ?>
            
            <?= $this->content ?>
            <hr>
            <footer>
                <p class="text-center">
                    &copy; <?= date('Y') ?>
                    <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
                </p>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>
